### ISSUE TITLE
Accessing coef_ after using BaggingPuClassifier with linear kernel leads to error

### ISSUE THREAD

**Issue by tomsilver** [pulearn/pulearn#11]
Hi, thanks a lot for making this package available! I ran into a small issue that is probably just due my lack of understanding the internals and may fall outside the intended usage.

The issue is that when using `BaggingPuClassifie`r on an `SVC` with a linear kernel, if I want to access the `coef_` after fitting, I get a crash. This works fine with `ElkanotoPuClassifier`, though. 

I'm using python 3.6.7 on macOS with scikit-learn==0.24.1

Here's a script to reproduce:

```
import numpy as np
from sklearn.svm import SVC
from sklearn.datasets import make_classification
from pulearn import ElkanotoPuClassifier, BaggingPuClassifier

def test1(X, y):
    # Fit SVC with linear kernel and print coefs
    estimator = SVC(
        C=10,
        kernel='linear',
        probability=True,
    )
    estimator.fit(X, y)
    print("Coefs:", estimator.coef_)

def test2(X ,y):
    # Use ElkanotoPuClassifier
    estimator = SVC(
        C=10,
        kernel='linear',
        probability=True,
    )
    pu_estimator = ElkanotoPuClassifier(estimator=estimator)
    pu_estimator.fit(X, y)
    print("Coefs:", estimator.coef_)

def test3(X ,y):
    # Use BaggingPuClassifier
    estimator = SVC(
        C=10,
        kernel='linear',
        probability=True,
    )
    pu_estimator = BaggingPuClassifier(base_estimator=estimator)
    pu_estimator.fit(X, y)
    print("Coefs:", estimator.coef_)

if __name__ == '__main__':
    X, y = make_classification(
        n_samples=300, #3000,
        n_features=20,
        n_informative=2,
        n_redundant=2,
        n_repeated=0,
        n_classes=2,
        n_clusters_per_class=2,
        weights=None,
        flip_y=0.01,
        class_sep=1.0,
        hypercube=True,
        shift=0.0,
        scale=1.0,
        shuffle=True,
        random_state=None,
    )
    y[np.where(y == 0)[0]] = -1.
    print("Running test 1")
    test1(X, y)
    print("Running test 2")
    test2(X, y)
    print("Running test 3")
    test3(X, y)
```
The resulting printout for me is:
```
$ python pu_test.py 
Running test 1
Coefs: [[ 0.0786472  -0.21331864 -0.10287062 -0.21610315  0.0737364   0.01255858
   0.02136734  0.88419459 -0.16436331  0.1868487   0.07473255  0.18643653
  -0.04270674 -0.07417686  0.04763841 -0.44191377  0.33058271 -0.30513276
   1.12576518  0.16788899]]
Running test 2
Coefs: [[ 0.06284581 -0.18227556 -0.14205543 -0.27219114  0.09877694  0.04750807
   0.00836287  0.87359828 -0.25730168  0.15666736  0.03739819  0.18452285
   0.02742696 -0.00708275  0.11718429 -0.46166503  0.37592076 -0.27631968
   1.11951729  0.12841216]]
Running test 3
Traceback (most recent call last):
  File "pu_test.py", line 62, in <module>
    test3(X, y)
  File "pu_test.py", line 36, in test3
    print("Coefs:", estimator.coef_)
  File "/Users/tom/.pyenv/versions/3.6.7/lib/python3.6/site-packages/sklearn/svm/_base.py", line 504, in coef_
    coef = self._get_coef()
  File "/Users/tom/.pyenv/versions/3.6.7/lib/python3.6/site-packages/sklearn/svm/_base.py", line 752, in _get_coef
    if self.dual_coef_.shape[0] == 1:
AttributeError: 'SVC' object has no attribute 'dual_coef_'
```
Thanks again!

**Comment by shaypal5** [comment]
Hey!

No problem - it's a simple mistake.

`BaggingPuClassifier` is an ensemble model. It uses the `estimator` object your provide it with as a template to generate *n* different estimators. You can learn more about the bagging approach to classification here:
https://en.wikipedia.org/wiki/Bootstrap_aggregating

Technically, this means that unlike with the Elkanoto classifier - which uses the actual classifier object your provide it with - it just uses it to create *other* classifier objects that get fitted.

Since the classifier you provide is never fitted, it is never initialized with the `coef_` attribute. :)

**Comment by tomsilver** [comment]
Makes total sense! Thanks for the explanation :)
